[package]
name = "si4p"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dependencies.iced]
version = "0.3"
features = [
	"wgpu", "image",
	"svg", "debug",
	"default_system_font",
	"tokio",
]

[dependencies.iced_futures]
version = "0.3"

[dependencies.iced_native]
version = "0.4"



[dependencies.lazy_static]
version = "1"



[dependencies.tokio]
package = "tokio"
version = "1.0"
features = ["rt", "rt-multi-thread", "time", "fs", "sync", "io-util"]



[dependencies.futures]
version = "0.3"



[dependencies.probe-rs]
version = "0.12.0"



[dependencies.tracing]
version = "0.1.31"
#git = "https://github.com/tokio-rs/tracing"
#branch = "master"
#features = ["std"]

[dependencies.tracing-subscriber]
version = "0.3.9"
features = ["default", "env-filter"]
#git = "https://github.com/tokio-rs/tracing"
#branch = "master"
#features = ["std"]



[dependencies.ron]
version = "0.7"

[dependencies.serde]
version = "1"
features = ["derive"]



[dependencies.regex]
version = "1"



[dependencies.architecture]
version = "*"
path = "architecture"

[dependencies.database]
version = "*"
path = "database"

[dependencies.einstein]
version = "0.1.0"
git = "https://github.com/micro-rust/einstein"

[dependencies.marcel]
version = "0.1.0"
git = "https://github.com/micro-rust/marcel"

[dependencies.probe]
version = "*"
path = "probe"
